name: dev
values:
  - key: url
    value: ''
  - key: access_token
    value: ''
  - key: quizId
    value: ''
  - key: mediaId
    value: ''
  - key: courseId
    value: ''
  - key: sectionId
    value: ''
  - key: categoryId
    value: ''
  - key: lessonId
    value: ''
